### ISSUE TITLE
get_monitors missing..

### ISSUE THREAD

**Issue by Velas2** [dille12/2dshooter#18]
C:\python\2dshooter>python RUN.py
pygame 2.1.2 (SDL 2.0.18, Python 3.7.4)
Hello from the pygame community. https://www.pygame.org/c
Traceback (most recent call last):
  File "RUN.py", line 6, in <module>
    from values import *
  File "C:\python\2dshooter\values.py", line 7, in <modul
    from screeninfo import get_monitors
ModuleNotFoundError: No module named 'screeninfo'

**Comment by Velas2** [comment]
I fail...ignore me :p
